volumes:
  datafiles:

networks:
  my-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.40
    container_name: somaiyacom-db
    environment:     
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: somaiya_com_stage
      MYSQL_USER: arigel
      MYSQL_PASSWORD: "t)2D#+qDgkG8U-MN"
    volumes:
      - datafiles:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - my-network
    restart: always

  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: somaiyacom-app
    environment:
      ENV: local  # Change to 'production' on AWS
      MYSQL_DBHOST: rds19may2025.cfuahjovyrht.ap-south-1.rds.amazonaws.com
      MYSQL_DATABASE: somaiya_com_stage
      MYSQL_DBUSER: arigel
      MYSQL_DBPASS: "t)2D#+qDgkG8U-MN"
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - my-network
